### ISSUE TITLE
Missing yousee epg data (They are available on yousee but not parsed into your script)

### ISSUE THREAD

**Issue by wazerstar** [ukdtom/epg-dk.bundle#27]
Checking https://tv.yousee.dk/tv-guide

Seeing that the data is available like
TV2 regions has epg feed but your script does not parse to all channels like TV2 Fyn or TV2 Østjylland

Another example is eurosport 2 does not get feed either but it shows up under yousees guide

There's many more, not checked your code but saw a dump of channels YouSee_ChannelList_20161202.txt

if it reads from there maybe it needs a new dump update

**Comment by ukdtom** [comment]
Channel list is read dynamically from the API, so if they doesn't show, then the API doesn't provide them.

Sorry, but nothing I can do about that.

I did however update the channel list, showing what we can fetch as of today
