### ISSUE TITLE
Rækkefølge af kanaler

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/epg-dk.bundle#30]
Følger YouSee API, men ville være rart, hvis man kunne matche eller lave sin egen rækkefølge

**Comment by ukdtom** [comment]
Note to self:
Idet Plugin Interface er limited, skal vi arbejde med en map fil, som folk må ændre efter behov

Vi skal også checke, at alle entries i Map filen har et match i det vi henter fra YouSee (Nye kanaler eller kanaler der forsvinder)

**Comment by EmilMoe** [comment]
Alternativt kan der laves et ekstern script, der reorganiserer listen. Så må man sætte dette op med crontab el.

**Comment by allanhoumark** [comment]
Er der mulighed for at få aktivitet på denne igen?

**Comment by ukdtom** [comment]
Idet plugin's er ved at dø, er det en opgave som jeg finder formålsløs, desværre

**Comment by allanhoumark** [comment]
Ved at dø, hvordan det?
Ændre plex på noget eller?

/Allan Houmark

**Comment by ukdtom** [comment]
https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

De fleste andre af mine små plugins er også gået stale, hvis det er store ændringer, desværre
