### ISSUE TITLE
Kanaler der mangler ift Waoo!

### ISSUE THREAD

**Issue by EmilMoe** [ukdtom/epg-dk.bundle#32]
Er der mulighed for at merge noget ind et sted?

* Uptown TV (dansk)
* Uptown Classic
* Pixel.tv
* France 24 

Det ville være fint, blot at have disse med uden en EPG eller en tom EPG.

**Comment by ukdtom** [comment]
Sorry, men out of scope for epg-dk

Men du kan evt. selv pille ved koden, eller den genererede xml fil
