### ISSUE TITLE
Problem med Formel 1 optagelser

### ISSUE THREAD

**Issue by fribse** [ukdtom/epg-dk.bundle#36]
Når der er Formel 1 på 3+ i år, ser det ud til at titlen blot er Formel 1, og ikke f.eks. Formel 1 - Spaniens Grand Prix.
Hvis man vælger at optage direkte i guiden, så finder den ikke nogen episoder, det ser dog ud til at man med lidt held kan få den til at optage, hvis man vælger at optage serien, så selvom den siger der ikke er nogen episoder, finder den optagelsen alligevel, men fejler så når den skal indstilles???
Det er rimeligt underligt.
Det ser ud til at kvalifikationen om lørdagen godt kan optages, men de hedder vist også Formel 1 - kvalifikation til Spaniens Grand Prix, såvidt jeg kan se.

**Comment by ukdtom** [comment]
Fixed med nyeste release
