### ISSUE TITLE
Only getting list of channels without a guide?

### ISSUE THREAD

**Issue by casperse** [ukdtom/epg-dk.bundle#37]
Hi since yesterday I only get a 58K file size.
I then installed the newest version of the plugin (That now have option to run manually - NICE!)
But same thing only get the listing, so either the source site have changed? or my setup is "Corrupted"

Happy Christmas and KUdos for creating this great plugin!

**Comment by ukdtom** [comment]
Hej med dig.

Kørsel 1 er for at hente kanal oversigten
Derefter laver du en mapping på din DVR imellem din tuners kanaler, og de kanaler som mit lille tool har hentet ned

Derefter skulle den gerne hente guiden for de valgte kanaler, og du burde kunne se dette i din XML fil

Og hvis ikke, skal jeg desværre bruge plugin logs

**Comment by casperse** [comment]
Øv vidste ikke at dit plug-in virkede på denne måde. Har brugt det i årevis!

Jeg havde fornyligt installeret xTeVe som så brugte din XML file som jeg troede var en selvstændig TV guide.

jeg er nemlig i en situation hvor jeg havde kanaler som ikke var en del af YouSee pakken og xTeVe kan bruge forskellige XML filer. Nå men så må jeg skifte tilbage.

Tak for svar og glædeligt Jul 👍

**Comment by ukdtom** [comment]
I lige måde, og sorry

**Comment by casperse** [comment]
En sidste ting :-)
Har nu opdateret til den nyeste version og kan ny lave et manuelt pull. (Forstår nu at det er vigtigt når man ændrer noget før opdatering af EPG.

Det ser ud som om at alle data nu hentes igen :-) , men to kanaler har ikke nogle data.
Prøvede et par dage.  Kan de være udgået fra siden, eller kan der være en anden grund til at disse 2 kanaler aldrig har nogle data efter "pull" på forhånd tak for det hurtige svar, synd man ikke kan mikse XML og PLex's egen guides, men din er stadig altid bedre! 

  <channel id="64">
    <display-name>6´eren</display-name>
    <display-name>64</display-name>
    <icon src="http://cloud.yousee.tv/static/img/logos/Large_6eren.png"/>
  </channel>

og

  <channel id="173">
    <display-name>EuroSport 2 HD</display-name>
    <display-name>173</display-name>
    <icon src="http://cloud.yousee.tv/static/img/logos/Large_Eurosport2.png"/>
  </channel>

**Comment by ukdtom** [comment]
YouSee ikke har EPG for de kanaler

https://play.yousee.dk/tv-guide/2023-12-21/12-00
